services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: going-dutch
      POSTGRES_USER: going-dutch
      POSTGRES_DB: going-dutch

volumes:
  postgres-data:
